// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEn-92YrK6u3Aea6Qvu2DzTP3bHwyOuRg',
    appId: '1:652090269752:web:be0314ca23d72498f886cd',
    messagingSenderId: '652090269752',
    projectId: 'pasal-35ed8',
    authDomain: 'pasal-35ed8.firebaseapp.com',
    storageBucket: 'pasal-35ed8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGE1KyIkhq0F01jC4sdWEMRCHVjPQMfgs',
    appId: '1:652090269752:android:19cfd57ffc9aa715f886cd',
    messagingSenderId: '652090269752',
    projectId: 'pasal-35ed8',
    storageBucket: 'pasal-35ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdeqoqAjy_blLZN_254yUVpzIS3EEbNU8',
    appId: '1:652090269752:ios:f2f6b097c37e678cf886cd',
    messagingSenderId: '652090269752',
    projectId: 'pasal-35ed8',
    storageBucket: 'pasal-35ed8.appspot.com',
    androidClientId: '652090269752-46pn2o43jcu0l44gg639sen1vjilnije.apps.googleusercontent.com',
    iosClientId: '652090269752-o6d5reudrr1s5l1c7bbadu7uk936a2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdeqoqAjy_blLZN_254yUVpzIS3EEbNU8',
    appId: '1:652090269752:ios:f2f6b097c37e678cf886cd',
    messagingSenderId: '652090269752',
    projectId: 'pasal-35ed8',
    storageBucket: 'pasal-35ed8.appspot.com',
    androidClientId: '652090269752-46pn2o43jcu0l44gg639sen1vjilnije.apps.googleusercontent.com',
    iosClientId: '652090269752-o6d5reudrr1s5l1c7bbadu7uk936a2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasal',
  );
}
